### ISSUE TITLE
Impossible to get the shift trajectories in the movie alignment of TiltSeriesM

### ISSUE THREAD

**Issue by danielmarchan3** [scipion-em/scipion-em-tomo#448] opened 2024-01-24 13:57 UTC
When I import TiltSeriesMovies and align them using any of the available methods (motioncorr, flexAlign), I only obtain the TiltSeriesImage without the associated alignment information (shifts). I am seeking a way to retrieve this information in order to create a consensus for tomo movie alignment.

**Comment by fede-pe** [comment] 2024-01-24 14:01
To complete this, the idea is that the tilt-series movies alignment algorithm retrieve also a new tilt-series movie object with the associated alignment matrix. This info is useful for consensus and validation.

**Comment by azazellochg** [comment] 2024-01-24 15:41
duplicate of #128

**Closed by azazellochg** 2024-01-24 15:41 UTC
