### ISSUE TITLE
report alignment in tilt-series movies alignment protocols

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-tomo#335] opened 2023-03-27 11:23 UTC
The requirement is equivalent to how it is implemented SPA. In order to develop consensus/quality analysis protocols in Scipion, the tilt-series movies with the assigned alignments are needed. Just an output SetOfTiltSeriesMovies with the same information as the input one plus a transform object containing the alignment is enough.

**Comment by azazellochg** [comment] 2024-01-24 15:41
duplicate of #128

**Closed by azazellochg** 2024-01-24 15:41 UTC
